export const SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION';
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';



export const USER_AUTH = 'USER_AUTH';
export const LOG_OUT = 'LOG_OUT';
