export const SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION';
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION';
export const CLEAR_ALERT = 'CLEAR_ALERT';


export const USER_AUTH = 'USER_AUTH';
